# SPDX-FileCopyrightText: 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Security Audit
on:
    schedule:
        - cron: 0 0 1,15 * *
    push:
        branches:
            - "*"
        paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'
    pull_request:
      paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'
    workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: security-audit-${{ github.workflow }}-${{ github.sha }}

jobs:
    security_audit:
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
              with:
                egress-policy: audit

            - name: Checkout
              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

            - name: Install Rust
              uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # stable
              with:
                toolchain: stable

            - name: Install cargo-audit
              uses: taiki-e/install-action@542cebaaed782771e619bd5609d97659d109c492 # v2.66.7
              with:
                tool: cargo-audit

            - name: Security Audit
              run: cargo audit
