# SPDX-FileCopyrightText: 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Security Audit
on:
    schedule:
        - cron: 0 0 1,15 * *
    push:
        branches:
            - "*"
        paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'
    pull_request:
      paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'
    workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: security-audit-${{ github.workflow }}-${{ github.sha }}

jobs:
    security_audit:
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
              with:
                egress-policy: audit

            - name: Checkout
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

            - name: Install Rust
              uses: dtolnay/rust-toolchain@686976e191b89faba57d3206551f0f330d8cb249 # stable
              with:
                toolchain: stable

            - name: Install cargo-audit
              uses: taiki-e/install-action@ab6895351a88b908e96a4697860d4ffea5e57dbe # v2.87.27
              with:
                tool: cargo-audit

            - name: Security Audit
              run: cargo audit
