# SPDX-FileCopyrightText: 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Code Coverage
on:
    workflow_call:

permissions:
  contents: read

concurrency:
  group: coverage-${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: false

jobs:
    test:
        name: Generate Coverage
        runs-on: ubuntu-latest
        container:
            image: xd009642/tarpaulin:develop-nightly@sha256:48118c4d716340b547ecee92b669fd26714390d243916cf969839eb0371acb37
            options: --security-opt seccomp=unconfined

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
              with:
                egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

            - uses: dtolnay/rust-toolchain@0e28dd9a7764e5f83064112bb1f24025a14c313c # nightly
              with:
                toolchain: nightly
                components: llvm-tools-preview

            - uses: taiki-e/install-action@861a07ce7084f55488e375df125cdc99bba60eb7 # v2.87.23
              with:
                tool: cargo-llvm-cov,nextest

            - name: Collect coverage data (including doctests)
              run: |
                cargo llvm-cov --no-report nextest --config-file nextest.toml
                cargo llvm-cov --no-report --doc
                cargo llvm-cov report --doctests --lcov --output-path lcov.info

            - name: Upload to codecov.io
              uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
              with:
                file: lcov.info
                token: ${{ secrets.CODECOV_TOKEN }}
                verbose: true
                working-directory: .

            - name: Upload to Codacy
              uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
              with:
                project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
                coverage-reports: lcov.info
