# SPDX-FileCopyrightText: 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Code Coverage
on:
    workflow_call:

permissions:
  contents: read

concurrency:
  group: coverage-${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: false

jobs:
    test:
        name: Generate Coverage
        runs-on: ubuntu-latest
        container:
            image: xd009642/tarpaulin:develop-nightly@sha256:3580ad00973edefc23c228ab02e271c282e237a9161f82a2adeba6c54b244ca1
            options: --security-opt seccomp=unconfined

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
              with:
                egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

            - uses: dtolnay/rust-toolchain@f0d5300ba8908d942c808f4d31c08471d7798ba3 # nightly
              with:
                toolchain: nightly
                components: llvm-tools-preview

            - uses: taiki-e/install-action@ab6895351a88b908e96a4697860d4ffea5e57dbe # v2.87.27
              with:
                tool: cargo-llvm-cov,nextest

            - name: Collect coverage data (including doctests)
              run: |
                cargo llvm-cov --no-report nextest --config-file nextest.toml
                cargo llvm-cov --no-report --doc
                cargo llvm-cov report --doctests --lcov --output-path lcov.info

            - name: Upload to codecov.io
              uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
              with:
                file: lcov.info
                token: ${{ secrets.CODECOV_TOKEN }}
                verbose: true
                working-directory: .

            - name: Upload to Codacy
              uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
              with:
                project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
                coverage-reports: lcov.info
